---
fixtures:
  repositories:
    named: "https://github.com/simp/pupmod-simp-named.git"
    rsync: "https://github.com/simp/pupmod-simp-rsync.git"
    stdlib: "https://github.com/simp/puppetlabs-stdlib.git"
    simplib: "https://github.com/simp/pupmod-simp-simplib.git"
    simpcat: "https://github.com/simp/pupmod-simp-simpcat.git"
  symlinks:
    resolv: "#{source_dir}"
